// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: eosio.token/proto/v1/eosio.token.proto

//package substreams.sink.eosio.token.v1;

package pbtokentransfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accounts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Account `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Accounts) Reset() {
	*x = Accounts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Accounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accounts) ProtoMessage() {}

func (x *Accounts) ProtoReflect() protoreflect.Message {
	mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accounts.ProtoReflect.Descriptor instead.
func (*Accounts) Descriptor() ([]byte, []int) {
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP(), []int{0}
}

func (x *Accounts) GetItems() []*Account {
	if x != nil {
		return x.Items
	}
	return nil
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// trace information
	TrxId       string `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	ActionIndex uint32 `protobuf:"varint,2,opt,name=action_index,json=actionIndex,proto3" json:"action_index,omitempty"`
	// contract & scope
	Contract string `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Symcode  string `protobuf:"bytes,4,opt,name=symcode,proto3" json:"symcode,omitempty"`
	// data payload
	Account      string `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Balance      string `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty"`
	BalanceDelta int64  `protobuf:"varint,7,opt,name=balance_delta,json=balanceDelta,proto3" json:"balance_delta,omitempty"`
	// extras
	Precision uint32  `protobuf:"varint,10,opt,name=precision,proto3" json:"precision,omitempty"`
	Amount    int64   `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Value     float64 `protobuf:"fixed64,12,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *Account) GetActionIndex() uint32 {
	if x != nil {
		return x.ActionIndex
	}
	return 0
}

func (x *Account) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *Account) GetSymcode() string {
	if x != nil {
		return x.Symcode
	}
	return ""
}

func (x *Account) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Account) GetBalanceDelta() int64 {
	if x != nil {
		return x.BalanceDelta
	}
	return 0
}

func (x *Account) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Account) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Account) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Stats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Stat `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *Stats) Reset() {
	*x = Stats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetItems() []*Stat {
	if x != nil {
		return x.Items
	}
	return nil
}

type Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// trace information
	TrxId       string `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	ActionIndex uint32 `protobuf:"varint,2,opt,name=action_index,json=actionIndex,proto3" json:"action_index,omitempty"`
	// contract & scope
	Contract string `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Symcode  string `protobuf:"bytes,4,opt,name=symcode,proto3" json:"symcode,omitempty"`
	// data payload
	Issuer      string `protobuf:"bytes,5,opt,name=issuer,proto3" json:"issuer,omitempty"`
	MaxSupply   string `protobuf:"bytes,6,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	Supply      string `protobuf:"bytes,7,opt,name=supply,proto3" json:"supply,omitempty"`
	SupplyDelta int64  `protobuf:"varint,8,opt,name=supply_delta,json=supplyDelta,proto3" json:"supply_delta,omitempty"`
	// extras
	Precision uint32  `protobuf:"varint,10,opt,name=precision,proto3" json:"precision,omitempty"`
	Amount    int64   `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Value     float64 `protobuf:"fixed64,12,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Stat) Reset() {
	*x = Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP(), []int{3}
}

func (x *Stat) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *Stat) GetActionIndex() uint32 {
	if x != nil {
		return x.ActionIndex
	}
	return 0
}

func (x *Stat) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *Stat) GetSymcode() string {
	if x != nil {
		return x.Symcode
	}
	return ""
}

func (x *Stat) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Stat) GetMaxSupply() string {
	if x != nil {
		return x.MaxSupply
	}
	return ""
}

func (x *Stat) GetSupply() string {
	if x != nil {
		return x.Supply
	}
	return ""
}

func (x *Stat) GetSupplyDelta() int64 {
	if x != nil {
		return x.SupplyDelta
	}
	return 0
}

func (x *Stat) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Stat) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Stat) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TransferEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*TransferEvent `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *TransferEvents) Reset() {
	*x = TransferEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEvents) ProtoMessage() {}

func (x *TransferEvents) ProtoReflect() protoreflect.Message {
	mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEvents.ProtoReflect.Descriptor instead.
func (*TransferEvents) Descriptor() ([]byte, []int) {
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP(), []int{4}
}

func (x *TransferEvents) GetItems() []*TransferEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

type TransferEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// transaction
	TrxId         string `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	ActionOrdinal uint32 `protobuf:"varint,2,opt,name=action_ordinal,json=actionOrdinal,proto3" json:"action_ordinal,omitempty"`
	// contract & scope
	Contract string `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Action   string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Symcode  string `protobuf:"bytes,5,opt,name=symcode,proto3" json:"symcode,omitempty"`
	// data payload
	From     string `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,7,opt,name=to,proto3" json:"to,omitempty"`
	Quantity string `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Memo     string `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	// extras
	Precision uint32  `protobuf:"varint,10,opt,name=precision,proto3" json:"precision,omitempty"`
	Amount    int64   `protobuf:"varint,11,opt,name=amount,proto3" json:"amount,omitempty"`
	Value     float64 `protobuf:"fixed64,12,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TransferEvent) Reset() {
	*x = TransferEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEvent) ProtoMessage() {}

func (x *TransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_eosio_token_proto_v1_eosio_token_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEvent.ProtoReflect.Descriptor instead.
func (*TransferEvent) Descriptor() ([]byte, []int) {
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP(), []int{5}
}

func (x *TransferEvent) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *TransferEvent) GetActionOrdinal() uint32 {
	if x != nil {
		return x.ActionOrdinal
	}
	return 0
}

func (x *TransferEvent) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *TransferEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TransferEvent) GetSymcode() string {
	if x != nil {
		return x.Symcode
	}
	return ""
}

func (x *TransferEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferEvent) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferEvent) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *TransferEvent) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *TransferEvent) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *TransferEvent) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransferEvent) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_eosio_token_proto_v1_eosio_token_proto protoreflect.FileDescriptor

var file_eosio_token_proto_v1_eosio_token_proto_rawDesc = []byte{
	0x0a, 0x26, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x2e, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x76,
	0x31, 0x22, 0x42, 0x0a, 0x08, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61,
	0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x9e, 0x02, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x72, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x72, 0x78, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72,
	0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70,
	0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12,
	0x33, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xb4, 0x02, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x74, 0x72, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x72, 0x78, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x75, 0x70,
	0x70, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3c, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61,
	0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xbb, 0x02, 0x0a, 0x0d,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x74, 0x72, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x72, 0x78, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x79, 0x6d, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x6d,
	0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x6d, 0x6f, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x61, 0x5a, 0x5f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x66, 0x61, 0x73, 0x74, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73,
	0x2d, 0x73, 0x69, 0x6e, 0x6b, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x61,
	0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x2f, 0x65, 0x6f, 0x73, 0x69, 0x6f, 0x2e, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eosio_token_proto_v1_eosio_token_proto_rawDescOnce sync.Once
	file_eosio_token_proto_v1_eosio_token_proto_rawDescData = file_eosio_token_proto_v1_eosio_token_proto_rawDesc
)

func file_eosio_token_proto_v1_eosio_token_proto_rawDescGZIP() []byte {
	file_eosio_token_proto_v1_eosio_token_proto_rawDescOnce.Do(func() {
		file_eosio_token_proto_v1_eosio_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_eosio_token_proto_v1_eosio_token_proto_rawDescData)
	})
	return file_eosio_token_proto_v1_eosio_token_proto_rawDescData
}

var file_eosio_token_proto_v1_eosio_token_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_eosio_token_proto_v1_eosio_token_proto_goTypes = []interface{}{
	(*Accounts)(nil),       // 0: antelope.eosio.token.v1.Accounts
	(*Account)(nil),        // 1: antelope.eosio.token.v1.Account
	(*Stats)(nil),          // 2: antelope.eosio.token.v1.Stats
	(*Stat)(nil),           // 3: antelope.eosio.token.v1.Stat
	(*TransferEvents)(nil), // 4: antelope.eosio.token.v1.TransferEvents
	(*TransferEvent)(nil),  // 5: antelope.eosio.token.v1.TransferEvent
}
var file_eosio_token_proto_v1_eosio_token_proto_depIdxs = []int32{
	1, // 0: antelope.eosio.token.v1.Accounts.items:type_name -> antelope.eosio.token.v1.Account
	3, // 1: antelope.eosio.token.v1.Stats.items:type_name -> antelope.eosio.token.v1.Stat
	5, // 2: antelope.eosio.token.v1.TransferEvents.items:type_name -> antelope.eosio.token.v1.TransferEvent
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_eosio_token_proto_v1_eosio_token_proto_init() }
func file_eosio_token_proto_v1_eosio_token_proto_init() {
	if File_eosio_token_proto_v1_eosio_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eosio_token_proto_v1_eosio_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Accounts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eosio_token_proto_v1_eosio_token_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eosio_token_proto_v1_eosio_token_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eosio_token_proto_v1_eosio_token_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eosio_token_proto_v1_eosio_token_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eosio_token_proto_v1_eosio_token_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eosio_token_proto_v1_eosio_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_eosio_token_proto_v1_eosio_token_proto_goTypes,
		DependencyIndexes: file_eosio_token_proto_v1_eosio_token_proto_depIdxs,
		MessageInfos:      file_eosio_token_proto_v1_eosio_token_proto_msgTypes,
	}.Build()
	File_eosio_token_proto_v1_eosio_token_proto = out.File
	file_eosio_token_proto_v1_eosio_token_proto_rawDesc = nil
	file_eosio_token_proto_v1_eosio_token_proto_goTypes = nil
	file_eosio_token_proto_v1_eosio_token_proto_depIdxs = nil
}
