// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: setabi/proto/v1/setabi.proto

package pbsetabi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetABIEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*SetABIEvent `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SetABIEvents) Reset() {
	*x = SetABIEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setabi_proto_v1_setabi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetABIEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetABIEvents) ProtoMessage() {}

func (x *SetABIEvents) ProtoReflect() protoreflect.Message {
	mi := &file_setabi_proto_v1_setabi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetABIEvents.ProtoReflect.Descriptor instead.
func (*SetABIEvents) Descriptor() ([]byte, []int) {
	return file_setabi_proto_v1_setabi_proto_rawDescGZIP(), []int{0}
}

func (x *SetABIEvents) GetItems() []*SetABIEvent {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetABIEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// transaction
	TrxId         string `protobuf:"bytes,1,opt,name=trx_id,json=trxId,proto3" json:"trx_id,omitempty"`
	ActionOrdinal uint32 `protobuf:"varint,2,opt,name=action_ordinal,json=actionOrdinal,proto3" json:"action_ordinal,omitempty"`
	// contract & action
	Contract string `protobuf:"bytes,3,opt,name=contract,proto3" json:"contract,omitempty"`
	Action   string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// data payload
	Account string `protobuf:"bytes,5,opt,name=account,proto3" json:"account,omitempty"`
	Abi     string `protobuf:"bytes,6,opt,name=abi,proto3" json:"abi,omitempty"`
}

func (x *SetABIEvent) Reset() {
	*x = SetABIEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_setabi_proto_v1_setabi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetABIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetABIEvent) ProtoMessage() {}

func (x *SetABIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_setabi_proto_v1_setabi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetABIEvent.ProtoReflect.Descriptor instead.
func (*SetABIEvent) Descriptor() ([]byte, []int) {
	return file_setabi_proto_v1_setabi_proto_rawDescGZIP(), []int{1}
}

func (x *SetABIEvent) GetTrxId() string {
	if x != nil {
		return x.TrxId
	}
	return ""
}

func (x *SetABIEvent) GetActionOrdinal() uint32 {
	if x != nil {
		return x.ActionOrdinal
	}
	return 0
}

func (x *SetABIEvent) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *SetABIEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SetABIEvent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SetABIEvent) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

var File_setabi_proto_v1_setabi_proto protoreflect.FileDescriptor

var file_setabi_proto_v1_setabi_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x74, 0x61, 0x62, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x65, 0x74, 0x61, 0x62, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x73, 0x65, 0x74, 0x61, 0x62, 0x69, 0x2e,
	0x76, 0x31, 0x22, 0x45, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x41, 0x42, 0x49, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x35, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x73, 0x65, 0x74,
	0x61, 0x62, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x42, 0x49, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x0b, 0x53, 0x65,
	0x74, 0x41, 0x42, 0x49, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x72, 0x78,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x72, 0x78, 0x49, 0x64,
	0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x62, 0x69, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x61, 0x62, 0x69, 0x42, 0x55, 0x5a, 0x53, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x66,
	0x61, 0x73, 0x74, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2d, 0x73,
	0x69, 0x6e, 0x6b, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x61, 0x64, 0x76,
	0x61, 0x6e, 0x63, 0x65, 0x64, 0x2f, 0x73, 0x65, 0x74, 0x61, 0x62, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x73, 0x65, 0x74, 0x61, 0x62, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_setabi_proto_v1_setabi_proto_rawDescOnce sync.Once
	file_setabi_proto_v1_setabi_proto_rawDescData = file_setabi_proto_v1_setabi_proto_rawDesc
)

func file_setabi_proto_v1_setabi_proto_rawDescGZIP() []byte {
	file_setabi_proto_v1_setabi_proto_rawDescOnce.Do(func() {
		file_setabi_proto_v1_setabi_proto_rawDescData = protoimpl.X.CompressGZIP(file_setabi_proto_v1_setabi_proto_rawDescData)
	})
	return file_setabi_proto_v1_setabi_proto_rawDescData
}

var file_setabi_proto_v1_setabi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_setabi_proto_v1_setabi_proto_goTypes = []interface{}{
	(*SetABIEvents)(nil), // 0: antelope.setabi.v1.SetABIEvents
	(*SetABIEvent)(nil),  // 1: antelope.setabi.v1.SetABIEvent
}
var file_setabi_proto_v1_setabi_proto_depIdxs = []int32{
	1, // 0: antelope.setabi.v1.SetABIEvents.items:type_name -> antelope.setabi.v1.SetABIEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_setabi_proto_v1_setabi_proto_init() }
func file_setabi_proto_v1_setabi_proto_init() {
	if File_setabi_proto_v1_setabi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_setabi_proto_v1_setabi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetABIEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_setabi_proto_v1_setabi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetABIEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_setabi_proto_v1_setabi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_setabi_proto_v1_setabi_proto_goTypes,
		DependencyIndexes: file_setabi_proto_v1_setabi_proto_depIdxs,
		MessageInfos:      file_setabi_proto_v1_setabi_proto_msgTypes,
	}.Build()
	File_setabi_proto_v1_setabi_proto = out.File
	file_setabi_proto_v1_setabi_proto_rawDesc = nil
	file_setabi_proto_v1_setabi_proto_goTypes = nil
	file_setabi_proto_v1_setabi_proto_depIdxs = nil
}
